version: "3.9"
services:

  #
  # janus-gateway
  #
  janus-gateway:
    build:
      context: .
    image: janus-gateway
    container_name: janus-gateway
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    volumes:
      - "./etc/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./etc/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg"
      - "./etc/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    restart: always
    networks:
      - janus_network

networks:
  janus_network:
    name: janus_network
    driver: bridge